package com.bautruc.ecommerce.commerce.domain;
import java.time.Instant;import jakarta.persistence.*;
@Entity @Table(name="checkout_operations")
public class CheckoutOperation{
 @Id @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="global_seq")@SequenceGenerator(name="global_seq",sequenceName="app_global_id_seq",allocationSize=1)private Long id;
 @Column(name="user_id",nullable=false)private Long userId;@Column(name="idempotency_key",nullable=false)private String idempotencyKey;@Column(name="request_hash",nullable=false,length=64)private String requestHash;@Enumerated(EnumType.STRING)@Column(nullable=false)private CheckoutOperationState state;
 @Column(name="order_id")private Long orderId;@Column(name="payment_id")private Long paymentId;@Column(name="processing_started_at")private Instant processingStartedAt;@Column(name="retry_count",nullable=false)private int retryCount;@Column(name="last_error_code")private String lastErrorCode;@Column(name="state_changed_at",nullable=false)private Instant stateChangedAt;@Column(name="completed_at")private Instant completedAt;@Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 protected CheckoutOperation(){}public Long getId(){return id;}public Long getUserId(){return userId;}public String getIdempotencyKey(){return idempotencyKey;}public String getRequestHash(){return requestHash;}public CheckoutOperationState getState(){return state;}public Long getOrderId(){return orderId;}public Long getPaymentId(){return paymentId;}public Instant getProcessingStartedAt(){return processingStartedAt;}public int getRetryCount(){return retryCount;}public String getLastErrorCode(){return lastErrorCode;}public Instant getStateChangedAt(){return stateChangedAt;}public Instant getCompletedAt(){return completedAt;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}
 public void localPrepared(Long orderId,Long paymentId,Instant now){if(state!=CheckoutOperationState.STARTED)throw new IllegalStateException("operation not started");this.orderId=orderId;this.paymentId=paymentId;state=CheckoutOperationState.LOCAL_PREPARED;stateChangedAt=now;updatedAt=now;}
 public void claimPayOSCreate(Instant now){if(state!=CheckoutOperationState.LOCAL_PREPARED)throw new IllegalStateException("operation not locally prepared");state=CheckoutOperationState.PAYOS_CREATING;processingStartedAt=now;retryCount++;stateChangedAt=now;updatedAt=now;}
 public void payOSCreated(Instant now){if(state!=CheckoutOperationState.PAYOS_CREATING&&state!=CheckoutOperationState.PAYOS_CREATED)throw new IllegalStateException("operation not creating");state=CheckoutOperationState.PAYOS_CREATED;processingStartedAt=null;lastErrorCode=null;stateChangedAt=now;updatedAt=now;}
 public void resetForRetry(Instant now){if(state!=CheckoutOperationState.PAYOS_CREATING)throw new IllegalStateException("operation not creating");state=CheckoutOperationState.LOCAL_PREPARED;processingStartedAt=null;stateChangedAt=now;updatedAt=now;}
 public void complete(Instant now){if(state==CheckoutOperationState.COMPLETED)return;if(state!=CheckoutOperationState.PAYOS_CREATED)throw new IllegalStateException("operation not provider-created");state=CheckoutOperationState.COMPLETED;completedAt=now;stateChangedAt=now;updatedAt=now;}
 public void fail(String errorCode,Instant now){if(state==CheckoutOperationState.FAILED)return;state=CheckoutOperationState.FAILED;processingStartedAt=null;lastErrorCode=errorCode;stateChangedAt=now;updatedAt=now;}
}
