package com.bautruc.ecommerce.cart.api;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.Instant;import com.bautruc.ecommerce.common.security.*;import com.bautruc.ecommerce.identity.domain.*;import com.bautruc.ecommerce.identity.infrastructure.UserJpaRepository;import com.fasterxml.jackson.databind.*;import jakarta.servlet.http.Cookie;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.MediaType;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.springframework.test.web.servlet.*;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Testcontainers
class CartInventoryApiIntegrationTest{
 @Container static final PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:16-alpine");
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);}
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired UserJpaRepository users;@Autowired JwtTokenService tokens;@Autowired JdbcTemplate jdbc;
 @BeforeEach void clean(){jdbc.execute("TRUNCATE TABLE collections, users CASCADE");}
 @Test void adminCreatesCatalogAndStockThenUserManagesRepricedCart()throws Exception{
  User admin=save("admin",UserRole.ADMIN),user=save("user",UserRole.USER);Cookie ac=access(admin),uc=access(user);
  long collection=id(mvc.perform(post("/api/v1/admin/collections").cookie(ac).with(csrf().asHeader()).contentType(MediaType.APPLICATION_JSON).content("{\"nameVi\":\"Gốm\",\"nameEn\":\"Pottery\",\"status\":\"ACTIVE\"}")).andExpect(status().isCreated()).andReturn());
  long product=id(mvc.perform(post("/api/v1/admin/products").cookie(ac).with(csrf().asHeader()).contentType(MediaType.APPLICATION_JSON).content("{\"nameVi\":\"Bình\",\"nameEn\":\"Vase\",\"basePrice\":100000,\"collectionId\":%d,\"status\":\"ACTIVE\"}".formatted(collection))).andExpect(status().isCreated()).andReturn());
  mvc.perform(post("/api/v1/admin/inventory/{id}/adjust",product).cookie(ac).with(csrf().asHeader()).contentType(MediaType.APPLICATION_JSON).content("{\"type\":\"IMPORT\",\"quantityChange\":10,\"reason\":\"Initial stock\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.availableQuantity").value(10));
  mvc.perform(get("/api/v1/admin/inventory").param("keyword","Bình").param("status","IN_STOCK").cookie(ac)).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalElements").value(1));
  mvc.perform(get("/api/v1/admin/inventory/{id}/transactions",product).cookie(ac)).andExpect(status().isOk()).andExpect(jsonPath("$.data.content[0].type").value("IMPORT"));
  mvc.perform(put("/api/v1/admin/products/{id}/discount",product).cookie(ac).with(csrf().asHeader()).contentType(MediaType.APPLICATION_JSON).content("{\"discountType\":\"FIXED_PRICE\",\"discountValue\":80000,\"startAt\":\"2020-01-01T00:00:00+07:00\",\"endAt\":\"2099-01-01T00:00:00+07:00\",\"isActive\":true}")).andExpect(status().isOk());
  MvcResult added=mvc.perform(post("/api/v1/cart/items").cookie(uc).with(csrf().asHeader()).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":%d,\"quantity\":2}".formatted(product))).andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].sellingPrice").value(80000)).andExpect(jsonPath("$.data.totalAmount").value(160000)).andReturn();
  long item=json.readTree(added.getResponse().getContentAsString()).path("data").path("items").get(0).path("id").asLong();
  mvc.perform(patch("/api/v1/cart/items/{id}",item).cookie(uc).with(csrf().asHeader()).contentType(MediaType.APPLICATION_JSON).content("{\"quantity\":3}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalAmount").value(240000));
  mvc.perform(delete("/api/v1/cart/items/{id}",item).cookie(uc).with(csrf().asHeader())).andExpect(status().isOk()).andExpect(jsonPath("$.data.items").isEmpty());
 }
 @Test void enforcesRolesCsrfAndStockValidation()throws Exception{User admin=save("admin2",UserRole.ADMIN),user=save("user2",UserRole.USER);Cookie ac=access(admin),uc=access(user);mvc.perform(get("/api/v1/admin/inventory").cookie(uc)).andExpect(status().isForbidden());mvc.perform(post("/api/v1/admin/collections").cookie(ac).contentType(MediaType.APPLICATION_JSON).content("{}" )).andExpect(status().isForbidden());long c=insertCollection(),p=insertProduct(c);mvc.perform(post("/api/v1/cart/items").cookie(uc).with(csrf().asHeader()).contentType(MediaType.APPLICATION_JSON).content("{\"productId\":%d,\"quantity\":1}".formatted(p))).andExpect(status().isConflict()).andExpect(jsonPath("$.error.code").value("INVENTORY_INSUFFICIENT"));}
 private long insertCollection(){return jdbc.queryForObject("insert into collections(name_vi,name_en,status,created_at,updated_at) values('A','A','ACTIVE',now(),now()) returning id",Long.class);}
 private long insertProduct(long c){long p=jdbc.queryForObject("insert into products(name_vi,name_en,base_price,status,collection_id,created_at,updated_at) values('P','P',100,'ACTIVE',?,now(),now()) returning id",Long.class,c);jdbc.update("insert into inventories(product_id,quantity,reserved_quantity,low_stock_threshold,updated_at) values(?,0,0,5,now())",p);return p;}
 private User save(String key,UserRole role){Instant n=Instant.now();return users.save(new User(key,key+"@example.com",key,null,role,UserStatus.ACTIVE,n,n));}
 private Cookie access(User u){return new Cookie(JwtAuthenticationFilter.ACCESS_COOKIE_NAME,tokens.createAccessToken(u));}
 private long id(MvcResult r)throws Exception{return json.readTree(r.getResponse().getContentAsString()).path("data").path("id").asLong();}
}
