package com.bautruc.ecommerce.commerce.application;
import java.time.Instant;import java.util.*;import com.bautruc.ecommerce.cart.application.*;import com.bautruc.ecommerce.catalog.application.*;import com.bautruc.ecommerce.commerce.domain.*;import com.bautruc.ecommerce.commerce.infrastructure.*;import com.bautruc.ecommerce.common.exception.BusinessException;import com.bautruc.ecommerce.common.time.BusinessClock;import com.bautruc.ecommerce.inventory.application.InventoryCommandService;import com.bautruc.ecommerce.order.application.*;import com.bautruc.ecommerce.payment.application.PaymentCommandService;import com.bautruc.ecommerce.payment.domain.Payment;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class CheckoutLocalPreparationService{
 private final CheckoutOperationJpaRepository operations;private final CheckoutOperationItemJpaRepository operationItems;private final CartCheckoutPort cart;private final ProductCheckoutQuery products;private final InventoryCommandService inventory;private final OrderCommandService orders;private final PaymentCommandService payments;private final BusinessClock clock;
 public CheckoutLocalPreparationService(CheckoutOperationJpaRepository o,CheckoutOperationItemJpaRepository oi,CartCheckoutPort c,ProductCheckoutQuery p,InventoryCommandService i,OrderCommandService os,PaymentCommandService ps,BusinessClock b){operations=o;operationItems=oi;cart=c;products=p;inventory=i;orders=os;payments=ps;clock=b;}
 @Transactional public CheckoutLocalPreparationResult prepare(Long operationId,Long userId,NormalizedCheckoutRequest request){CheckoutOperation op=operations.findByIdForUpdate(operationId).orElseThrow();if(!op.getUserId().equals(userId))throw new BusinessException("ACCESS_DENIED","Checkout operation does not belong to current user.");if(op.getState()==CheckoutOperationState.LOCAL_PREPARED)return existing(op);if(op.getState()!=CheckoutOperationState.STARTED)throw new BusinessException(CommerceErrorCodes.CHECKOUT_IN_PROGRESS,"Checkout is being processed.");Instant now=clock.now();CartSnapshot snapshot=cart.lockAndSnapshot(userId);List<OrderLineCommand> lines=new ArrayList<>();Map<Long,Long> quantities=new LinkedHashMap<>();try{for(CartItemSnapshot item:snapshot.items()){ProductCheckoutView p=products.requirePurchasable(item.productId(),now);lines.add(new OrderLineCommand(p.id(),p.nameVi(),p.nameEn(),p.basePrice(),p.sellingPrice(),item.quantity()));quantities.put(p.id(),(long)item.quantity());}}catch(ArithmeticException e){throw new BusinessException("CART_INVALID","Cart total is invalid.");}
  inventory.validateReservable(quantities);CreatedOrder created;try{created=orders.create(new CreateOrderCommand(userId,request.receiverName(),request.phone(),request.email(),request.address(),request.note(),List.copyOf(lines)),now);}catch(ArithmeticException e){throw new BusinessException("CART_INVALID","Cart total is invalid.");}inventory.reserve(created.order().getId(),quantities,now);Payment payment=payments.createPending(created.order().getId(),created.order().getTotalAmount(),now);operationItems.saveAll(snapshot.items().stream().map(i->new CheckoutOperationItem(op.getId(),i.cartItemId(),i.cartItemVersion(),i.productId(),i.quantity())).toList());op.localPrepared(created.order().getId(),payment.getId(),now);return new CheckoutLocalPreparationResult(op.getId(),created.order().getId(),created.order().getOrderCode(),payment.getId(),created.order().getTotalAmount(),op.getState());}
 private CheckoutLocalPreparationResult existing(CheckoutOperation op){return new CheckoutLocalPreparationResult(op.getId(),op.getOrderId(),null,op.getPaymentId(),0,op.getState());}
}
