package com.bautruc.ecommerce.order.application;
import java.time.*;import java.util.*;import com.bautruc.ecommerce.common.exception.*;import com.bautruc.ecommerce.common.time.BusinessClock;import com.bautruc.ecommerce.order.api.response.*;import com.bautruc.ecommerce.order.domain.*;import com.bautruc.ecommerce.order.infrastructure.*;import com.bautruc.ecommerce.payment.application.*;import com.bautruc.ecommerce.payment.domain.Payment;import com.bautruc.ecommerce.payment.domain.PaymentStatus;import jakarta.persistence.criteria.Root;import jakarta.persistence.criteria.Subquery;import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class OrderQueryService implements OrderOwnershipQuery{
 private final OrderJpaRepository orders;private final OrderItemJpaRepository items;private final PaymentQueryPort payments;private final BusinessClock clock;public OrderQueryService(OrderJpaRepository o,OrderItemJpaRepository i,PaymentQueryPort p,BusinessClock c){orders=o;items=i;payments=p;clock=c;}
 @Transactional(readOnly=true)public Page<OrderSummaryResponse> mine(Long userId,Integer page,Integer size){Page<Order> result=orders.findByUserId(userId,page(page,size,Sort.by(Sort.Direction.DESC,"createdAt")));Map<Long,PaymentStatus> statuses=statuses(result.getContent());return result.map(o->summary(o,statuses.get(o.getId())));}
 @Transactional(readOnly=true)public OrderDetailResponse mineDetail(Long userId,Long id){Order o=orders.findByIdAndUserId(id,userId).orElseThrow(()->new ResourceNotFoundException(OrderErrorCodes.ORDER_NOT_OWNER,"Order not found for current user."));return detail(o);}
 @Transactional(readOnly=true)public OrderDetailResponse adminDetail(Long id){return detail(required(id));}
 @Transactional(readOnly=true)public Page<OrderSummaryResponse> adminList(String keyword,OrderStatus orderStatus,PaymentStatus paymentStatus,LocalDate from,LocalDate to,Integer page,Integer size,String sort){Specification<Order> spec=Specification.where(null);if(keyword!=null&&!keyword.isBlank()){String like="%"+keyword.trim().toLowerCase(Locale.ROOT)+"%";String phone="%"+keyword.replaceAll("\\s+","")+"%";spec=spec.and((r,q,cb)->cb.or(cb.like(cb.lower(r.get("orderCode")),like),cb.like(cb.lower(r.get("receiverName")),like),cb.like(cb.lower(r.get("email")),like),cb.like(cb.function("replace",String.class,r.get("phone"),cb.literal(" "),cb.literal("")),phone)));}if(orderStatus!=null)spec=spec.and((r,q,cb)->cb.equal(r.get("status"),orderStatus));if(paymentStatus!=null)spec=spec.and((r,q,cb)->{Subquery<Long> sub=q.subquery(Long.class);Root<Payment> payment=sub.from(Payment.class);sub.select(payment.get("orderId")).where(cb.equal(payment.get("orderId"),r.get("id")),cb.equal(payment.get("status"),paymentStatus));return cb.exists(sub);});if(from!=null){Instant start=clock.startOfDay(from);spec=spec.and((r,q,cb)->cb.greaterThanOrEqualTo(r.get("createdAt"),start));}if(to!=null){Instant end=clock.startOfNextDay(to);spec=spec.and((r,q,cb)->cb.lessThan(r.get("createdAt"),end));}Page<Order> result=orders.findAll(spec,page(page,size,sort(sort)));Map<Long,PaymentStatus> statuses=statuses(result.getContent());return result.map(o->summary(o,statuses.get(o.getId())));}
 @Override @Transactional(readOnly=true)public boolean isOwner(Long orderId,Long userId){return orders.findByIdAndUserId(orderId,userId).isPresent();}
 private OrderDetailResponse detail(Order o){PaymentOrderSnapshot payment=payments.forOrderSnapshot(o.getId());return new OrderDetailResponse(o.getId(),o.getOrderCode(),o.getUserId(),o.getReceiverName(),o.getPhone(),o.getEmail(),o.getAddress(),o.getNote(),items.findByOrderIdOrderById(o.getId()).stream().map(OrderItemResponse::from).toList(),o.getTotalAmount(),o.getTotalAmount(),o.getStatus(),payment.status(),payment.id(),payment.amount(),payment.checkoutUrl(),payment.qrCode(),payment.expiresAt(),o.getCreatedAt(),o.getUpdatedAt());}
 private Order required(Long id){return orders.findById(id).orElseThrow(()->new ResourceNotFoundException(OrderErrorCodes.ORDER_NOT_FOUND,"Order not found."));}private Map<Long,PaymentStatus> statuses(Collection<Order> source){return payments.statusesForOrders(source.stream().map(Order::getId).toList());}private OrderSummaryResponse summary(Order o,PaymentStatus p){return new OrderSummaryResponse(o.getId(),o.getOrderCode(),o.getCreatedAt(),o.getTotalAmount(),o.getStatus(),p);}private Pageable page(Integer p,Integer s,Sort sort){return PageRequest.of(p==null?0:Math.max(0,p),s==null?20:Math.min(Math.max(1,s),100),sort);}private Sort sort(String raw){if(raw==null||raw.isBlank())return Sort.by(Sort.Direction.DESC,"createdAt");String[] a=raw.split(",",2);String field=Set.of("createdAt","totalAmount","orderCode").contains(a[0])?a[0]:"createdAt";return Sort.by(a.length>1&&a[1].equalsIgnoreCase("asc")?Sort.Direction.ASC:Sort.Direction.DESC,field);}
}
