package com.bautruc.ecommerce.cart.application;
import java.util.*;import com.bautruc.ecommerce.cart.api.response.*;import com.bautruc.ecommerce.cart.domain.*;import com.bautruc.ecommerce.cart.infrastructure.*;import com.bautruc.ecommerce.catalog.application.*;
import com.bautruc.ecommerce.common.exception.*;import com.bautruc.ecommerce.common.security.*;import com.bautruc.ecommerce.common.time.BusinessClock;import com.bautruc.ecommerce.inventory.application.*;
import org.springframework.http.HttpStatus;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class CartApplicationService implements CartCheckoutPort{
 private final CartJpaRepository carts;private final CartItemJpaRepository items;private final ProductCheckoutQuery products;private final InventoryAvailabilityQuery inventory;private final CurrentUserProvider currentUser;private final BusinessClock clock;
 public CartApplicationService(CartJpaRepository c,CartItemJpaRepository i,ProductCheckoutQuery p,InventoryAvailabilityQuery a,CurrentUserProvider u,BusinessClock b){carts=c;items=i;products=p;inventory=a;currentUser=u;clock=b;}
 @Transactional(readOnly=true) public CartResponse view(){Long user=userId();Optional<Cart> cart=carts.findByUserId(user);if(cart.isEmpty())return new CartResponse(List.of(),0);return response(items.findByCartIdOrderByCreatedAtAsc(cart.get().getId()));}
 @Transactional public CartResponse add(Long productId,int quantity){Long user=userId();ProductCheckoutView product=products.requirePurchasable(productId);carts.ensureCart(user,clock.now());Cart cart=carts.findByUserIdForUpdate(user).orElseThrow();Optional<CartItem> existing=items.findByCartIdAndProductId(cart.getId(),productId);int resulting;try{resulting=Math.addExact(existing.map(CartItem::getQuantity).orElse(0),quantity);}catch(ArithmeticException e){throw invalid();}validateAvailable(product.id(),resulting);if(existing.isPresent())existing.get().setQuantity(resulting,clock.now());else items.save(new CartItem(cart.getId(),productId,resulting,clock.now()));cart.touch(clock.now());return response(items.findByCartIdOrderByCreatedAtAsc(cart.getId()));}
 @Transactional public CartResponse update(Long itemId,int quantity){Cart cart=lockedUserCart();CartItem item=ownedItem(cart,itemId);products.requirePurchasable(item.getProductId());validateAvailable(item.getProductId(),quantity);item.setQuantity(quantity,clock.now());cart.touch(clock.now());return response(items.findByCartIdOrderByCreatedAtAsc(cart.getId()));}
 @Transactional public CartResponse remove(Long itemId){Cart cart=lockedUserCart();CartItem item=ownedItem(cart,itemId);items.delete(item);cart.touch(clock.now());return response(items.findByCartIdOrderByCreatedAtAsc(cart.getId()));}
 @Override @Transactional(readOnly=true) public CartSnapshot snapshot(Long userId){Cart c=carts.findByUserId(userId).orElseThrow(()->new BusinessException(CartErrorCodes.CART_EMPTY,"Cart is empty."));List<CartItemSnapshot> result=items.findByCartIdOrderByCreatedAtAsc(c.getId()).stream().map(i->new CartItemSnapshot(i.getId(),i.getVersion(),i.getProductId(),i.getQuantity())).toList();if(result.isEmpty())throw new BusinessException(CartErrorCodes.CART_EMPTY,"Cart is empty.");return new CartSnapshot(c.getId(),userId,result);}
 @Override @Transactional public CartSnapshot lockAndSnapshot(Long userId){Cart c=carts.findByUserIdForUpdate(userId).orElseThrow(()->new BusinessException(CartErrorCodes.CART_EMPTY,"Cart is empty."));List<CartItemSnapshot> result=items.findByCartIdOrderByCreatedAtAsc(c.getId()).stream().map(i->new CartItemSnapshot(i.getId(),i.getVersion(),i.getProductId(),i.getQuantity())).toList();if(result.isEmpty())throw new BusinessException(CartErrorCodes.CART_EMPTY,"Cart is empty.");return new CartSnapshot(c.getId(),userId,List.copyOf(result));}
 @Override @Transactional public void clearCheckedOutItems(Long userId,CartSnapshot snapshot){if(snapshot==null||!Objects.equals(userId,snapshot.userId()))throw invalid();Cart c=carts.findByUserIdForUpdate(userId).orElseThrow(()->new BusinessException(CartErrorCodes.CART_EMPTY,"Cart is empty."));if(!Objects.equals(c.getId(),snapshot.cartId()))throw invalid();snapshot.items().forEach(i->items.deleteSnapshot(i.cartItemId(),c.getId(),i.cartItemVersion()));c.touch(clock.now());}
 @Override @Transactional public void clearCheckedOutItems(Long userId,List<CartItemSnapshot> snapshots){Cart c=carts.findByUserIdForUpdate(userId).orElseThrow(()->new BusinessException(CartErrorCodes.CART_EMPTY,"Cart is empty."));snapshots.forEach(i->items.deleteSnapshot(i.cartItemId(),c.getId(),i.cartItemVersion()));c.touch(clock.now());}
 private CartResponse response(List<CartItem> source){List<CartItemResponse> out=new ArrayList<>();long total=0;try{for(CartItem i:source){ProductCheckoutView p=products.requirePurchasable(i.getProductId());long line=Math.multiplyExact(p.sellingPrice(),i.getQuantity());total=Math.addExact(total,line);out.add(new CartItemResponse(i.getId(),p.id(),p.nameVi(),p.nameEn(),p.thumbnailUrl(),i.getQuantity(),p.basePrice(),p.sellingPrice(),line,inventory.available(p.id())));}}catch(ArithmeticException e){throw invalid();}return new CartResponse(List.copyOf(out),total);}
 private void validateAvailable(Long productId,int requested){if(inventory.available(productId)<requested)throw new BusinessException(InventoryErrorCodes.INVENTORY_INSUFFICIENT,"Insufficient inventory.",HttpStatus.CONFLICT);}
 private Cart lockedUserCart(){return carts.findByUserIdForUpdate(userId()).orElseThrow(()->new ResourceNotFoundException(CartErrorCodes.CART_ITEM_NOT_FOUND,"Cart item not found."));}
 private CartItem ownedItem(Cart c,Long id){return items.findByIdAndCartId(id,c.getId()).orElseThrow(()->new ResourceNotFoundException(CartErrorCodes.CART_ITEM_NOT_FOUND,"Cart item not found."));}
 private Long userId(){return currentUser.currentUser().orElseThrow(()->new AccessDeniedException("Authentication required")).userId();}
 private BusinessException invalid(){return new BusinessException(CartErrorCodes.CART_INVALID,"Invalid cart state.");}
}
