package com.bautruc.ecommerce.commerce.application;
import java.util.Locale;import com.bautruc.ecommerce.commerce.api.request.CheckoutRequest;import com.bautruc.ecommerce.commerce.api.response.CheckoutResponse;import com.bautruc.ecommerce.commerce.domain.*;import com.bautruc.ecommerce.common.exception.BusinessException;import com.bautruc.ecommerce.common.security.*;import com.bautruc.ecommerce.payment.application.PaymentErrorCodes;import org.springframework.http.HttpStatus;import org.springframework.security.access.AccessDeniedException;import org.springframework.stereotype.Service;
@Service public class CheckoutApplicationService{
 private final CurrentUserProvider current;private final CheckoutRequestHasher hasher;private final CheckoutOperationService operations;private final CheckoutLocalPreparationService preparation;private final CheckoutStateService states;private final CheckoutPayOSService payos;private final CheckoutFinalizationService finalization;private final CheckoutResponseService responses;
 public CheckoutApplicationService(CurrentUserProvider c,CheckoutRequestHasher h,CheckoutOperationService o,CheckoutLocalPreparationService p,CheckoutStateService s,CheckoutPayOSService ps,CheckoutFinalizationService f,CheckoutResponseService r){current=c;hasher=h;operations=o;preparation=p;states=s;payos=ps;finalization=f;responses=r;}
 public CheckoutResponse checkout(String key,CheckoutRequest raw){AuthenticatedUser user=current.currentUser().orElseThrow(()->new AccessDeniedException("Authentication required"));NormalizedCheckoutRequest request=normalize(raw,user.email());CheckoutOperation op=operations.acquire(user.userId(),key,hasher.hash(request));if(op.getState()==CheckoutOperationState.STARTED){preparation.prepare(op.getId(),user.userId(),request);op=states.required(op.getId());}if(op.getState()==CheckoutOperationState.LOCAL_PREPARED){payos.create(op.getId());op=states.required(op.getId());}if(op.getState()==CheckoutOperationState.PAYOS_CREATING)throw new BusinessException(CommerceErrorCodes.CHECKOUT_IN_PROGRESS,"Checkout is being processed.",HttpStatus.ACCEPTED);if(op.getState()==CheckoutOperationState.PAYOS_CREATED){finalization.finalizeCheckout(op.getId());op=states.required(op.getId());}if(op.getState()==CheckoutOperationState.COMPLETED)return responses.build(op);throw new BusinessException(PaymentErrorCodes.PAYOS_REQUEST_FAILED,"Checkout payment creation failed.",HttpStatus.BAD_GATEWAY);}
 private NormalizedCheckoutRequest normalize(CheckoutRequest r,String fallbackEmail){String email=r.email()==null||r.email().isBlank()?fallbackEmail:r.email();return new NormalizedCheckoutRequest(trim(r.receiverName()),trim(r.phone()),trim(email).toLowerCase(Locale.ROOT),trim(r.address()),nullable(r.note()));}
 private String trim(String v){return v==null?null:v.trim();}private String nullable(String v){if(v==null||v.isBlank())return null;return v.trim();}
}
