package com.bautruc.ecommerce.catalog.application;
import java.util.List;import java.util.Locale;import java.util.Set;
import com.bautruc.ecommerce.catalog.api.request.*;import com.bautruc.ecommerce.catalog.domain.*;import com.bautruc.ecommerce.catalog.infrastructure.*;
import com.bautruc.ecommerce.common.exception.*;import com.bautruc.ecommerce.common.time.BusinessClock;import com.bautruc.ecommerce.inventory.application.InventoryInitializationPort;
import org.springframework.data.domain.*;import org.springframework.data.jpa.domain.Specification;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class CatalogService implements ProductCheckoutQuery{
 private final ProductJpaRepository products;private final ProductSearchRepository productSearch;private final CollectionJpaRepository collections;private final DiscountJpaRepository discounts;private final PricingService pricing;private final BusinessClock clock;private final InventoryInitializationPort inventory;private final ProductImageService imageService;
 public CatalogService(ProductJpaRepository p,ProductSearchRepository productSearch,CollectionJpaRepository c,DiscountJpaRepository d,PricingService pricing,BusinessClock clock,InventoryInitializationPort inventory,ProductImageService imageService){products=p;this.productSearch=productSearch;collections=c;discounts=d;this.pricing=pricing;this.clock=clock;this.inventory=inventory;this.imageService=imageService;}
 @Transactional public Product createProduct(ProductRequest r){requireCollection(r.collectionId());Product p=products.save(new Product(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.basePrice(),r.status(),r.collectionId(),clock.now()));inventory.initialize(p.getId());return p;}
 @Transactional public Product updateProduct(Long id,ProductRequest r){Product p=requireProduct(id);requireCollection(r.collectionId());discounts.findByProductId(id).ifPresent(d->validateDiscount(r.basePrice(),d.getType(),d.getValue(),d.getStartAt(),d.getEndAt()));p.update(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.basePrice(),r.status(),r.collectionId(),clock.now());return p;}
 @Transactional public Product updateProductStatus(Long id,ProductStatus status){Product p=requireProduct(id);p.update(p.getNameVi(),p.getNameEn(),p.getDescriptionVi(),p.getDescriptionEn(),p.getBasePrice(),status,p.getCollectionId(),clock.now());return p;}
 @Transactional public void deleteProduct(Long id){requireProduct(id).delete(clock.now());}
 @Transactional public ProductCollection createCollection(CollectionRequest r){return collections.save(new ProductCollection(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.status(),clock.now()));}
 @Transactional public ProductCollection updateCollection(Long id,CollectionRequest r){ProductCollection c=requireCollection(id);c.update(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.status(),clock.now());return c;}
 @Transactional public ProductCollection updateCollectionStatus(Long id,CollectionStatus status){ProductCollection c=requireCollection(id);c.update(c.getNameVi(),c.getNameEn(),c.getDescriptionVi(),c.getDescriptionEn(),status,clock.now());return c;}
 @Transactional public void deleteCollection(Long id){ProductCollection c=requireCollection(id);if(products.existsByCollectionIdAndDeletedAtIsNull(id))throw new BusinessException(CatalogErrorCodes.COLLECTION_NOT_EMPTY,"Collection still contains products.",HttpStatus.CONFLICT);c.delete(clock.now());}
 @Transactional public Discount upsertDiscount(Long productId,DiscountRequest r){Product p=requireProduct(productId);validateDiscount(p.getBasePrice(),r.discountType(),r.discountValue(),r.startAt().toInstant(),r.endAt().toInstant());return discounts.findByProductId(productId).map(d->{d.update(r.discountType(),r.discountValue(),r.startAt().toInstant(),r.endAt().toInstant(),r.isActive(),clock.now());return d;}).orElseGet(()->discounts.save(new Discount(productId,r.discountType(),r.discountValue(),r.startAt().toInstant(),r.endAt().toInstant(),r.isActive(),clock.now())));}
 @Transactional public Discount updateDiscountActive(Long productId,boolean active){requireProduct(productId);Discount d=discounts.findByProductId(productId).orElseThrow(()->new ResourceNotFoundException(CatalogErrorCodes.DISCOUNT_NOT_FOUND,"Discount not found."));d.update(d.getType(),d.getValue(),d.getStartAt(),d.getEndAt(),active,clock.now());return d;}
 @Transactional public void deleteDiscount(Long productId){requireProduct(productId);discounts.deleteByProductId(productId);}
 @Transactional(readOnly=true) public Product requireProduct(Long id){return products.findByIdAndDeletedAtIsNull(id).orElseThrow(()->new ResourceNotFoundException(CatalogErrorCodes.PRODUCT_NOT_FOUND,"Product not found."));}
 @Transactional(readOnly=true) public ProductCollection requireCollection(Long id){return collections.findByIdAndDeletedAtIsNull(id).orElseThrow(()->new ResourceNotFoundException(CatalogErrorCodes.COLLECTION_NOT_FOUND,"Collection not found."));}
 @Transactional(readOnly=true) public Page<Product> adminProducts(String keyword,ProductStatus status,Long collectionId,int page,int size,String sort){Specification<Product> spec=(root,q,cb)->cb.isNull(root.get("deletedAt"));if(keyword!=null&&!keyword.isBlank()){String like="%"+keyword.trim().toLowerCase(Locale.ROOT)+"%";spec=spec.and((r,q,cb)->cb.or(cb.like(cb.lower(r.get("nameVi")),like),cb.like(cb.lower(r.get("nameEn")),like)));}if(status!=null)spec=spec.and((r,q,cb)->cb.equal(r.get("status"),status));if(collectionId!=null)spec=spec.and((r,q,cb)->cb.equal(r.get("collectionId"),collectionId));return products.findAll(spec,page(page,size,sort,Set.of("createdAt","updatedAt","nameVi","nameEn","basePrice","status")));}
 @Transactional(readOnly=true) public Page<ProductCollection> adminCollections(String keyword,CollectionStatus status,int page,int size,String sort){Specification<ProductCollection> spec=(root,q,cb)->cb.isNull(root.get("deletedAt"));if(keyword!=null&&!keyword.isBlank()){String like="%"+keyword.trim().toLowerCase(Locale.ROOT)+"%";spec=spec.and((r,q,cb)->cb.or(cb.like(cb.lower(r.get("nameVi")),like),cb.like(cb.lower(r.get("nameEn")),like)));}if(status!=null)spec=spec.and((r,q,cb)->cb.equal(r.get("status"),status));return collections.findAll(spec,page(page,size,sort,Set.of("createdAt","updatedAt","nameVi","nameEn","status")));}
 @Transactional(readOnly=true) public java.util.Optional<Discount> discount(Long productId){return discounts.findByProductId(productId);}
 @Transactional(readOnly=true) public Page<Product> publicProducts(ProductSearchCriteria criteria){return productSearch.searchPublic(criteria);}
 @Transactional(readOnly=true) public List<ProductCollection> publicCollections(){return collections.findByStatusAndDeletedAtIsNullOrderByCreatedAtDesc(CollectionStatus.ACTIVE);}
 @Transactional(readOnly=true) public long sellingPrice(Product p){return pricing.sellingPrice(p);}
 @Override @Transactional(readOnly=true) public ProductCheckoutView requirePurchasable(Long id){Product p=requireProduct(id);if(!p.isPurchasable())throw new BusinessException(CatalogErrorCodes.PRODUCT_NOT_PURCHASABLE,"Product is not purchasable.");return new ProductCheckoutView(p.getId(),p.getNameVi(),p.getNameEn(),imageService.thumbnailUrl(p.getId()),p.getBasePrice(),pricing.sellingPrice(p));}
 @Override @Transactional(readOnly=true) public ProductCheckoutView requirePurchasable(Long id,java.time.Instant pricingAt){Product p=requireProduct(id);if(!p.isPurchasable())throw new BusinessException(CatalogErrorCodes.PRODUCT_NOT_PURCHASABLE,"Product is not purchasable.");return new ProductCheckoutView(p.getId(),p.getNameVi(),p.getNameEn(),imageService.thumbnailUrl(p.getId()),p.getBasePrice(),pricing.sellingPrice(p,pricingAt));}
 private void validateDiscount(long basePrice,DiscountType type,java.math.BigDecimal value,java.time.Instant startAt,java.time.Instant endAt){if(!startAt.isBefore(endAt))invalid();if(type==DiscountType.PERCENTAGE){if(value.compareTo(java.math.BigDecimal.ZERO)<=0||value.compareTo(new java.math.BigDecimal("100"))>=0)invalid();long price=java.math.BigDecimal.valueOf(basePrice).subtract(java.math.BigDecimal.valueOf(basePrice).multiply(value).divide(new java.math.BigDecimal("100"))).setScale(0,java.math.RoundingMode.HALF_UP).longValueExact();if(price<=0)invalid();}if(type==DiscountType.FIXED_PRICE&&(value.stripTrailingZeros().scale()>0||value.compareTo(java.math.BigDecimal.ZERO)<=0||value.compareTo(java.math.BigDecimal.valueOf(basePrice))>=0))invalid();}
 private void invalid(){throw new BusinessException(CatalogErrorCodes.DISCOUNT_INVALID,"Invalid discount.");}
 private Pageable page(int p,int s,String raw,Set<String> allowed){String[] parts=raw==null||raw.isBlank()?new String[]{"createdAt","desc"}:raw.split(",",2);String field=allowed.contains(parts[0])?parts[0]:"createdAt";Sort.Direction direction=parts.length>1&&parts[1].equalsIgnoreCase("asc")?Sort.Direction.ASC:Sort.Direction.DESC;return PageRequest.of(Math.max(0,p),Math.min(Math.max(1,s),100),Sort.by(direction,field).and(Sort.by(direction,"id")));}
}
