package com.bautruc.ecommerce.catalog.application;
import java.util.List;
import com.bautruc.ecommerce.catalog.api.request.*;import com.bautruc.ecommerce.catalog.domain.*;import com.bautruc.ecommerce.catalog.infrastructure.*;
import com.bautruc.ecommerce.common.exception.*;import com.bautruc.ecommerce.common.time.BusinessClock;import com.bautruc.ecommerce.inventory.application.InventoryInitializationPort;
import org.springframework.data.domain.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service
public class CatalogService implements ProductCheckoutQuery{
 private final ProductJpaRepository products;private final CollectionJpaRepository collections;private final DiscountJpaRepository discounts;private final PricingService pricing;private final BusinessClock clock;private final InventoryInitializationPort inventory;private final ProductImageService imageService;
 public CatalogService(ProductJpaRepository p,CollectionJpaRepository c,DiscountJpaRepository d,PricingService pricing,BusinessClock clock,InventoryInitializationPort inventory,ProductImageService imageService){products=p;collections=c;discounts=d;this.pricing=pricing;this.clock=clock;this.inventory=inventory;this.imageService=imageService;}
 @Transactional public Product createProduct(ProductRequest r){requireCollection(r.collectionId());Product p=products.save(new Product(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.basePrice(),r.status(),r.collectionId(),clock.now()));inventory.initialize(p.getId());return p;}
 @Transactional public Product updateProduct(Long id,ProductRequest r){Product p=requireProduct(id);requireCollection(r.collectionId());p.update(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.basePrice(),r.status(),r.collectionId(),clock.now());return p;}
 @Transactional public void deleteProduct(Long id){requireProduct(id).delete(clock.now());}
 @Transactional public ProductCollection createCollection(CollectionRequest r){return collections.save(new ProductCollection(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.status(),clock.now()));}
 @Transactional public ProductCollection updateCollection(Long id,CollectionRequest r){ProductCollection c=requireCollection(id);c.update(r.nameVi(),r.nameEn(),r.descriptionVi(),r.descriptionEn(),r.status(),clock.now());return c;}
 @Transactional public void deleteCollection(Long id){ProductCollection c=requireCollection(id);if(products.existsByCollectionIdAndDeletedAtIsNull(id))throw new BusinessException(CatalogErrorCodes.COLLECTION_NOT_EMPTY,"Collection still contains products.",HttpStatus.CONFLICT);c.delete(clock.now());}
 @Transactional public Discount upsertDiscount(Long productId,DiscountRequest r){Product p=requireProduct(productId);validateDiscount(p,r);return discounts.findByProductId(productId).map(d->{d.update(r.discountType(),r.discountValue(),r.startAt().toInstant(),r.endAt().toInstant(),r.isActive(),clock.now());return d;}).orElseGet(()->discounts.save(new Discount(productId,r.discountType(),r.discountValue(),r.startAt().toInstant(),r.endAt().toInstant(),r.isActive(),clock.now())));}
 @Transactional public void deleteDiscount(Long productId){requireProduct(productId);discounts.deleteByProductId(productId);}
 @Transactional(readOnly=true) public Product requireProduct(Long id){return products.findByIdAndDeletedAtIsNull(id).orElseThrow(()->new ResourceNotFoundException(CatalogErrorCodes.PRODUCT_NOT_FOUND,"Product not found."));}
 @Transactional(readOnly=true) public ProductCollection requireCollection(Long id){return collections.findByIdAndDeletedAtIsNull(id).orElseThrow(()->new ResourceNotFoundException(CatalogErrorCodes.COLLECTION_NOT_FOUND,"Collection not found."));}
 @Transactional(readOnly=true) public Page<Product> publicProducts(int page,int size){return products.findByStatusAndDeletedAtIsNull(ProductStatus.ACTIVE,PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100),Sort.by(Sort.Direction.DESC,"createdAt")));}
 @Transactional(readOnly=true) public List<ProductCollection> publicCollections(){return collections.findByStatusAndDeletedAtIsNullOrderByCreatedAtDesc(CollectionStatus.ACTIVE);}
 @Transactional(readOnly=true) public long sellingPrice(Product p){return pricing.sellingPrice(p);}
 @Override @Transactional(readOnly=true) public ProductCheckoutView requirePurchasable(Long id){Product p=requireProduct(id);if(!p.isPurchasable())throw new BusinessException(CatalogErrorCodes.PRODUCT_NOT_PURCHASABLE,"Product is not purchasable.");return new ProductCheckoutView(p.getId(),p.getNameVi(),p.getNameEn(),imageService.thumbnailUrl(p.getId()),p.getBasePrice(),pricing.sellingPrice(p));}
 @Override @Transactional(readOnly=true) public ProductCheckoutView requirePurchasable(Long id,java.time.Instant pricingAt){Product p=requireProduct(id);if(!p.isPurchasable())throw new BusinessException(CatalogErrorCodes.PRODUCT_NOT_PURCHASABLE,"Product is not purchasable.");return new ProductCheckoutView(p.getId(),p.getNameVi(),p.getNameEn(),imageService.thumbnailUrl(p.getId()),p.getBasePrice(),pricing.sellingPrice(p,pricingAt));}
 private void validateDiscount(Product p,DiscountRequest r){if(!r.startAt().isBefore(r.endAt()))invalid();if(r.discountType()==DiscountType.PERCENTAGE&&r.discountValue().compareTo(new java.math.BigDecimal("100"))>=0)invalid();if(r.discountType()==DiscountType.FIXED_PRICE&&(r.discountValue().stripTrailingZeros().scale()>0||r.discountValue().compareTo(java.math.BigDecimal.valueOf(p.getBasePrice()))>=0))invalid();}
 private void invalid(){throw new BusinessException(CatalogErrorCodes.DISCOUNT_INVALID,"Invalid discount.");}
}
