package com.bautruc.ecommerce.payment.domain;
import java.time.Instant;import jakarta.persistence.*;
@Entity @Table(name="payments")
public class Payment{
 @Id @GeneratedValue(strategy=GenerationType.SEQUENCE,generator="global_seq")@SequenceGenerator(name="global_seq",sequenceName="app_global_id_seq",allocationSize=1)private Long id;
 @Column(name="order_id",nullable=false,unique=true)private Long orderId;@Enumerated(EnumType.STRING)@Column(nullable=false)private PaymentProvider provider;@Enumerated(EnumType.STRING)@Column(nullable=false)private PaymentStatus status;@Column(nullable=false)private long amount;
 @Column(name="provider_payment_link_id")private String providerPaymentLinkId;@Column(name="external_transaction_identifier")private String externalTransactionIdentifier;@Column(name="checkout_url")private String checkoutUrl;@Column(name="qr_code")private String qrCode;
 @Column(name="created_at",nullable=false)private Instant createdAt;@Column(name="expires_at",nullable=false)private Instant expiresAt;@Column(name="paid_at")private Instant paidAt;@Column(name="refunded_at")private Instant refundedAt;@Column(name="refunded_by_user_id")private Long refundedByUserId;@Column(name="manual_refund_note")private String manualRefundNote;@Column(name="manual_resolution_required",nullable=false)private boolean manualResolutionRequired;@Column(name="manual_resolution_note")private String manualResolutionNote;@Column(name="updated_at",nullable=false)private Instant updatedAt;
 protected Payment(){}public Payment(Long orderId,long amount,Instant now){if(orderId==null||amount<=0)throw new IllegalArgumentException("invalid payment");this.orderId=orderId;this.amount=amount;provider=PaymentProvider.PAYOS;status=PaymentStatus.PENDING;createdAt=now;expiresAt=now.plusSeconds(900);updatedAt=now;}
 public Long getId(){return id;}public Long getOrderId(){return orderId;}public PaymentProvider getProvider(){return provider;}public PaymentStatus getStatus(){return status;}public long getAmount(){return amount;}public String getProviderPaymentLinkId(){return providerPaymentLinkId;}public String getExternalTransactionIdentifier(){return externalTransactionIdentifier;}public String getCheckoutUrl(){return checkoutUrl;}public String getQrCode(){return qrCode;}public Instant getCreatedAt(){return createdAt;}public Instant getExpiresAt(){return expiresAt;}public Instant getPaidAt(){return paidAt;}public Instant getRefundedAt(){return refundedAt;}public Long getRefundedByUserId(){return refundedByUserId;}public String getManualRefundNote(){return manualRefundNote;}public boolean isManualResolutionRequired(){return manualResolutionRequired;}public String getManualResolutionNote(){return manualResolutionNote;}public Instant getUpdatedAt(){return updatedAt;}
 public void markPaid(Instant at){if(status!=PaymentStatus.PENDING)throw new IllegalStateException("invalid payment state");status=PaymentStatus.PAID;paidAt=at;updatedAt=at;}
 public void captureProvider(String linkId,String url,String qr,Instant now){if(status!=PaymentStatus.PENDING)throw new IllegalStateException("invalid payment state");if(linkId==null||linkId.isBlank())throw new IllegalArgumentException("payment link id required");if(providerPaymentLinkId!=null&&!providerPaymentLinkId.equals(linkId))throw new IllegalStateException("provider link conflict");providerPaymentLinkId=linkId;checkoutUrl=url;qrCode=qr;updatedAt=now;}
 public void markPaid(String reference,Instant at){if(status==PaymentStatus.PAID)return;if(status!=PaymentStatus.PENDING)throw new IllegalStateException("invalid payment state");status=PaymentStatus.PAID;externalTransactionIdentifier=reference;paidAt=at;updatedAt=at;}
 public void markTerminal(PaymentStatus target,Instant now){if(target!=PaymentStatus.FAILED&&target!=PaymentStatus.CANCELLED&&target!=PaymentStatus.EXPIRED)throw new IllegalArgumentException("invalid terminal state");if(status==target)return;if(status!=PaymentStatus.PENDING)throw new IllegalStateException("invalid payment state");status=target;updatedAt=now;}
 public void requireManualResolution(String note,Instant now){manualResolutionRequired=true;manualResolutionNote=note;updatedAt=now;}
 public void refund(Long adminId,String note,Instant now){if(status==PaymentStatus.REFUNDED)return;if(status!=PaymentStatus.PAID)throw new IllegalStateException("invalid payment state");status=PaymentStatus.REFUNDED;refundedAt=now;refundedByUserId=adminId;manualRefundNote=note;updatedAt=now;}
}
