package com.bautruc.ecommerce.inventory.application;
import static org.assertj.core.api.Assertions.*;
import java.time.Instant;import java.util.*;import java.util.concurrent.*;
import com.bautruc.ecommerce.catalog.api.request.*;import com.bautruc.ecommerce.catalog.application.CatalogService;import com.bautruc.ecommerce.catalog.domain.*;import com.bautruc.ecommerce.cart.application.*;import com.bautruc.ecommerce.cart.infrastructure.CartJpaRepository;import com.bautruc.ecommerce.common.exception.BusinessException;import com.bautruc.ecommerce.identity.domain.*;import com.bautruc.ecommerce.identity.infrastructure.UserJpaRepository;import com.bautruc.ecommerce.inventory.domain.*;import com.bautruc.ecommerce.inventory.infrastructure.*;
import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.test.context.*;import org.testcontainers.containers.PostgreSQLContainer;import org.testcontainers.junit.jupiter.*;
@SpringBootTest @ActiveProfiles("test") @Testcontainers
class InventoryConcurrencyIntegrationTest{
 @Container static final PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:16-alpine");
 @DynamicPropertySource static void db(DynamicPropertyRegistry r){r.add("spring.datasource.url",postgres::getJdbcUrl);r.add("spring.datasource.username",postgres::getUsername);r.add("spring.datasource.password",postgres::getPassword);}
 @Autowired CatalogService catalog;@Autowired InventoryCommandService inventory;@Autowired InventoryQueryService inventoryQueries;@Autowired InventoryJpaRepository inventories;@Autowired InventoryTransactionJpaRepository transactions;@Autowired CartJpaRepository carts;@Autowired CartCheckoutPort cartCheckout;@Autowired UserJpaRepository users;@Autowired JdbcTemplate jdbc;
 @BeforeEach void clean(){jdbc.execute("TRUNCATE TABLE collections, users CASCADE");}
 @Test void concurrentLastItemReservationAllowsExactlyOneOrder()throws Exception{long product=product();inventory.adjust(product,InventoryTransactionType.IMPORT,1,"seed",null);ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch ready=new CountDownLatch(2),start=new CountDownLatch(1);Callable<Boolean> first=reserveTask(101L,product,ready,start),second=reserveTask(102L,product,ready,start);Future<Boolean>a=pool.submit(first),b=pool.submit(second);ready.await(5,TimeUnit.SECONDS);start.countDown();assertThat(List.of(a.get(10,TimeUnit.SECONDS),b.get(10,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);pool.shutdownNow();Inventory state=inventories.findByProductId(product).orElseThrow();assertThat(state.getQuantity()).isEqualTo(1);assertThat(state.getReservedQuantity()).isEqualTo(1);assertThat(transactions.findAll().stream().filter(t->t.getType()==InventoryTransactionType.RESERVE)).hasSize(1);}
 @Test void businessKeyMakesReserveIdempotentAndCartCreationUnique(){long product=product();inventory.adjust(product,InventoryTransactionType.IMPORT,5,"seed",null);inventory.reserve(200L,Map.of(product,2L));inventory.reserve(200L,Map.of(product,2L));assertThat(inventories.findByProductId(product).orElseThrow().getReservedQuantity()).isEqualTo(2);assertThat(transactions.findAll().stream().filter(t->t.getType()==InventoryTransactionType.RESERVE)).hasSize(1);User u=user();Instant now=Instant.now();carts.ensureCart(u.getId(),now);carts.ensureCart(u.getId(),now);assertThat(carts.count()).isEqualTo(1);}
 @Test void databaseRejectsDuplicateInventoryBusinessKey(){long product=product();Instant n=Instant.now();InventoryTransaction one=new InventoryTransaction(product,InventoryTransactionType.RESERVE,0,1,1,1,0,1,"ORDER",1L,"RESERVE:ORDER:1:PRODUCT:"+product,null,null,n);InventoryTransaction two=new InventoryTransaction(product,InventoryTransactionType.RESERVE,0,1,1,1,0,1,"ORDER",1L,"RESERVE:ORDER:1:PRODUCT:"+product,null,null,n);transactions.saveAndFlush(one);assertThatThrownBy(()->transactions.saveAndFlush(two)).isInstanceOf(DataIntegrityViolationException.class);}
 @Test void supportsCompleteInventoryLifecycleWithExactAudit(){long product=product();inventory.adjust(product,InventoryTransactionType.IMPORT,10,"seed",null);inventory.adjust(product,InventoryTransactionType.ADJUSTMENT,-2,"count correction",null);inventory.reserve(301L,Map.of(product,4L));inventory.release(301L,Map.of(product,4L));inventory.reserve(302L,Map.of(product,3L));inventory.sale(302L,Map.of(product,3L));inventory.restore(302L,Map.of(product,3L));Inventory state=inventories.findByProductId(product).orElseThrow();assertThat(state.getQuantity()).isEqualTo(8);assertThat(state.getReservedQuantity()).isZero();assertThat(transactions.findAll().stream().map(InventoryTransaction::getType)).contains(InventoryTransactionType.IMPORT,InventoryTransactionType.ADJUSTMENT,InventoryTransactionType.RESERVE,InventoryTransactionType.RELEASE,InventoryTransactionType.SALE,InventoryTransactionType.CANCEL_ORDER);}
 @Test void checkoutClearPreservesItemsChangedAfterSnapshot(){long product=product();User u=user();Instant now=Instant.now();carts.ensureCart(u.getId(),now);long cartId=carts.findByUserId(u.getId()).orElseThrow().getId();long itemId=jdbc.queryForObject("insert into cart_items(cart_id,product_id,quantity,version,created_at,updated_at) values(?,?,2,0,now(),now()) returning id",Long.class,cartId,product);CartSnapshot old=cartCheckout.snapshot(u.getId());jdbc.update("update cart_items set quantity=3, version=version+1, updated_at=now() where id=?",itemId);cartCheckout.clearCheckedOutItems(u.getId(),old);assertThat(jdbc.queryForObject("select count(*) from cart_items where id=?",Long.class,itemId)).isEqualTo(1);cartCheckout.clearCheckedOutItems(u.getId(),cartCheckout.snapshot(u.getId()));assertThat(jdbc.queryForObject("select count(*) from cart_items where id=?",Long.class,itemId)).isZero();}
 @Test void availableQuantitySortUsesDatabasePaginationBoundary(){long low=product();long high=product();long middle=product();inventory.adjust(low,InventoryTransactionType.IMPORT,5,"seed",null);inventory.adjust(high,InventoryTransactionType.IMPORT,20,"seed",null);inventory.adjust(middle,InventoryTransactionType.IMPORT,10,"seed",null);inventory.reserve(901L,Map.of(low,4L));inventory.reserve(902L,Map.of(middle,3L));var page0=inventoryQueries.list(null,null,0,2,"availableQuantity,asc");var page1=inventoryQueries.list(null,null,1,2,"availableQuantity,asc");assertThat(page0.getContent()).extracting(Inventory::getProductId).containsExactly(low,middle);assertThat(page1.getContent()).extracting(Inventory::getProductId).containsExactly(high);assertThat(page0.getTotalElements()).isEqualTo(3);}
 private Callable<Boolean> reserveTask(long order,long product,CountDownLatch ready,CountDownLatch start){return()->{ready.countDown();start.await();try{inventory.reserve(order,Map.of(product,1L));return true;}catch(BusinessException e){assertThat(e.code()).isEqualTo(InventoryErrorCodes.INVENTORY_INSUFFICIENT);return false;}};}
 private long product(){var c=catalog.createCollection(new CollectionRequest("C","C",null,null,CollectionStatus.ACTIVE));return catalog.createProduct(new ProductRequest("P","P",null,null,100L,c.getId(),ProductStatus.ACTIVE)).getId();}
 private User user(){Instant n=Instant.now();return users.save(new User(UUID.randomUUID().toString(),UUID.randomUUID()+"@example.com","U",null,UserRole.USER,UserStatus.ACTIVE,n,n));}
}
